#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Running ESLint..."
npm run lint || exit 1

echo "🔨 Building the project..."
npm run build || exit 1

echo "✅ Pre-commit hook completed successfully!"
